### ISSUE TITLE
 cert manager is not creating  the cert and secret in  CP4MCM 1.3 release 

### ISSUE THREAD

**Issue by abhishek-tyagi87** [IBM/ibm-cert-manager-operator#80]
cert manager is not creating  the cert and secret for CP4MCM 1.3 release .,installing CP4MCM 1.3, but  below auth  pods are  not  creating due to  volume mount setup  is failed, looks like secrets are not creating for these  pods, 
root@bnode:/opt/ibm-multicloud-manager-1.3/cluster# kubectl get po -n kube-system
NAME                                   READY   STATUS              RESTARTS   AGE
auth-idp-hscx4                         0/4     ContainerCreating   0          23m
auth-idp-n9gqb                         0/4     ContainerCreating   0          23m
auth-idp-wr2v5                         0/4     ContainerCreating   0          23m
auth-pap-dhhs7                         0/2     ContainerCreating   0          22m
auth-pap-xb4dd                         0/2     ContainerCreating   0          22m
auth-pap-zvwxb                         0/2     ContainerCreating   0          22m
auth-pdp-2w82k                         0/2     Init:0/1            0          22m
auth-pdp-tfvld                         0/2     Init:0/1            0          22m
auth-pdp-ws9xj                         0/2     Init:0/1            0          22m
default-http-backend-85548f5bb-vm5kc   1/1     Running             0          23m
icp-management-ingress-94n9v           0/1     ContainerCreating   0          23m
icp-management-ingress-fkr5t           0/1     ContainerCreating   0          23m
icp-management-ingress-tngh5           0/1     ContainerCreating   0          23m
icp-mongodb-0                          2/2     Running             0          28m
icp-mongodb-1                          2/2     Running             0          26m
icp-mongodb-2                          2/2     Running             0          25m
internal-management-ingress-hzl4k      0/1     ContainerCreating   0          23m
internal-management-ingress-pflws      0/1     ContainerCreating   0          23m
internal-management-ingress-zcgds      0/1     ContainerCreating   0          23m
nginx-ingress-controller-c26hs         1/1     Running             0          23m
nginx-ingress-controller-glc5j         1/1     Running             0          23m
oidc-client-registration-ct7j2         1/1     Running             0          23m
platform-api-c4c5bf6b6-kknfh           1/1     Running             0          23m
platform-api-c4c5bf6b6-vkdtw           1/1     Running             0          23m
platform-api-c4c5bf6b6-vlxjx           1/1     Running             0          23m
tiller-deploy-f68457b9-sb7g9           1/1     Running             0          67m
root@bnode:/opt/ibm-multicloud-manager-1.3/cluster#
 attach or mount for pod "kube-system"/"auth-idp-pj9rm". list of unmounted volumes=[platform-identity-management auth-key identity-provider-crt router-certs mongodb-client-cert]. list of unattached volumes=[journal platform-ident
ity-management shared logrotate logrotate-conf auth-key identity-provider-crt ldaps-ca-cert ibmid-jwk-cert ibmid-ssl-cert router-certs cluster-ca mongodb-ca-cert mongodb-client-cert default-token-mnwqs]
21m         Normal    Scheduled                pod/auth-idp-wr2v5                          Successfully assigned kube-system/auth-idp-wr2v5 to control1.ocp.dryrun.com
15m         Warning   FailedMount              pod/auth-idp-wr2v5                          MountVolume.SetUp failed for volume "platform-identity-management" : secret "platform-identity-management" not found
21m         Warning   FailedMount              pod/auth-idp-wr2v5                          MountVolume.SetUp failed for volume "auth-key" : secret "platform-auth-secret" not found
11m         Warning   FailedMount              pod/auth-idp-wr2v5                          MountVolume.SetUp failed for volume "router-certs" : secret "icp-management-ingress-tls-secret" not found
21m         Warning   FailedMount              pod/auth-idp-wr2v5                          MountVolume.SetUp failed for volume "identity-provider-crt" : secret "identity-provider-secret" not found
21m         Warning   FailedMount              pod/auth-idp-wr2v5                          MountVolume.SetUp failed for volume "mongodb-client-cert" : secret "icp-mongodb-client-cert" not found

Taylor George  1 day ago
@yanni

Abhishek Tyagi  1 day ago
@yanni  can you please help me

Yanni Zhang  1 day ago
it seems the cert manager did not create the cert and secret, is the pod running?

Abhishek Tyagi  23 hours ago
hi @yanni  cert manager pods are running .

Abhishek Tyagi  23 hours ago
root@bnode:/opt/ibm-multicloud-manager-1.3/cluster# kubectl get po -n cert-manager
NAME                                             READY   STATUS    RESTARTS   AGE
cert-manager-7898d857b6-7vztj                    1/1     Running   1          15d
cert-manager-cainjector-64d8bb6d4c-2fb4s         1/1     Running   0          41h
cert-manager-cainjector-64d8bb6d4c-rl478         0/1     Evicted   0          15d
cert-manager-controller-69b674c4f8-qrrfn         1/1     Running   0          21h
cert-manager-ibm-cert-manager-85d6cb4f48-7k4rv   1/1     Running   0          21h
root@bnode:/opt/ibm-multicloud-manager-1.3/cluster#

Abhishek Tyagi  23 hours ago
and i have seen some ubnormal logs for cert-manager-controller pod .

Abhishek Tyagi  23 hours ago
root@bnode:/opt/ibm-multicloud-manager-1.3/cluster# kubectl logs cert-manager-controller-69b674c4f8-qrrfn -n cert-manager |more
I0722 09:48:02.065177       1 main.go:64] setting up client for manager
I0722 09:48:02.065704       1 main.go:72] setting up manager
I0722 09:48:11.175803       1 main.go:79] Registering Components.
I0722 09:48:11.175822       1 main.go:82] setting up scheme
I0722 09:48:11.175993       1 main.go:89] Setting up controller
I0722 09:48:11.176046       1 main.go:95] setting up webhooks
I0722 09:48:11.177727       1 main.go:119] Starting the Cmd.
Waiting for policies to be available for processing...
W0722 09:48:11.299847       1 reflector.go:299] pkg/mod/k8s.io/client-go@v0.0.0-20190918160344-1fbdaa4c8d90/tools/cache/reflector.go:96: watch of *v1alpha1.CertificatePolicy ended with: too old resource version: 194851249 (194851
250)
Waiting for policies to be available for processing...
Waiting for policies to be available for processing...
Waiting for policies to be available for processing...
Waiting for policies to be available for processing...
Waiting for policies to be available for processing...
Waiting for policies to be available for processing...
Waiting for policies to be available for processing...
Waiting for policies to be available for processing...
Waiting for policies to be available for processing...
Waiting for policies to be available for processing...
Waiting for policies to be available for processing...
Waiting for policies to be available for processing...
Waiting for policies to be available for processing...

Yanni Zhang  17 hours ago
@swati.nair ^^ can you check? iam and mongo client certs and secrets are not created[
[cert-manager-ibm-cert-manager-85d6cb4f48-7k4rv_logs.txt](https://github.com/IBM/ibm-cert-manager-operator/files/4970437/cert-manager-ibm-cert-manager-85d6cb4f48-7k4rv_logs.txt)
](url)

**Comment by swati-nair** [comment]
@abhishek-tyagi87 as after discussion, you have already opened a duplicate issue in our internal repo, can we close this?
