### ISSUE TITLE
can't start cert-manager service

### ISSUE THREAD

**Issue by chenzhiwei** [IBM/ibm-cert-manager-operator#9]
several issues:

1. The cert-manager operator only reconciles the `default` name, but the name here is `example-certmanager`.

> {"level":"debug","ts":1581998907.8546846,"logger":"controller-runtime.manager.events","msg":"Warning","object":{"kind":"CertManager","name":"example-certmanager","uid":"a679b9d3-99cf-402d-aefa-9b71abd1f424","apiVersion":"operator.ibm.com/v1alpha1","resourceVersion":"354216"},"reason":"Not Allowed","message":"Only one CR named default is allowed"}

https://github.com/IBM/ibm-cert-manager-operator/blob/master/deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v2.0.0.clusterserviceversion.yaml#L11

2. After fixed the CR name issue, still another issue that can't find pullsecret

https://github.com/IBM/ibm-cert-manager-operator/blob/master/deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v2.0.0.clusterserviceversion.yaml#L17

> {"level":"error","ts":1581999082.376683,"logger":"controller_certmanager","msg":"Neither pull secret exist","error":"secrets \"The image pull secret my-pull-secret does not exist in the deploy namespace cert-manager and there was no copy pull secret found in the  namespace\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/prow/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/ibm/ibm-cert-manager-operator/pkg/controller/certmanager.imagePullSecret\n\t/home/prow/go/src/github.com/IBM/ibm-cert-manager-operator/pkg/controller/certmanager/prereqs.go:111\ngithub.com/ibm/ibm-cert-manager-operator/pkg/controller/certmanager.checkRbac\n\t/home/prow/go/src/github.com/IBM/ibm-cert-manager-operator/pkg/controller/certmanager/prereqs.go:42\ngithub.com/ibm/ibm-cert-manager-operator/pkg/controller/certmanager.(*ReconcileCertManager).PreReqs\n\t/home/prow/go/src/github.com/IBM/ibm-cert-manager-operator/pkg/controller/certmanager/certmanager_controller.go:261\ngithub.com/ibm/ibm-cert-manager-operator/pkg/controller/certmanager.(*ReconcileCertManager).Reconcile\n\t/home/prow/go/src/github.com/IBM/ibm-cert-manager-operator/pkg/controller/certmanager/certmanager_controller.go:233\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}

3. the cert-manager operator image is public, so no need to define pull secret here

https://github.com/IBM/ibm-cert-manager-operator/blob/master/deploy/olm-catalog/ibm-cert-manager-operator/3.5.0/ibm-cert-manager-operator.v2.0.0.clusterserviceversion.yaml#L305

**Comment by Crystal-Chun** [comment]
PR has been created and the new CSVs have been pushed to quay.io/application https://quay.io/application/opencloudio/ibm-cert-manager-operator-app?tab=settings

**Comment by chenzhiwei** [comment]
still has errors, the cert-manage namespace not found.

could you put the cert-manager service into same namespace as cert-manager operator?

> {"level":"error","ts":1582096654.4470708,"logger":"controller_certmanager","msg":"One or more prerequisites not met, requeueing","error":"namespaces \"cert-manager\" not found","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/prow/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\ngithub.com/ibm/ibm-cert-manager-operator/pkg/controller/certmanager.(*ReconcileCertManager).Reconcile\n\t/home/prow/go/src/github.com/IBM/ibm-cert-manager-operator/pkg/controller/certmanager/certmanager_controller.go:234\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/home/prow/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/prow/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20191004115801-a2eda9f80ab8/pkg/util/wait/wait.go:88"}

**Comment by Crystal-Chun** [comment]
@chenzhiwei When we deploy the operand, we check for the namespace cert-manager and create it if it doesn't exist. How did it hit this error? The operator should've created that namespace and I've rechecked that the latest code in master does so. 


Is there an extra set of permissions needed to create a namespace? May I have access to the environment where this was hit?

**Comment by Crystal-Chun** [comment]
cert-manager service runs, closing issue. Please reopen if more issues are faced.
